name: Deploy to VPS

on:
  push:
    branches:
      - main  # Sprawdź czy Twoja główna gałąź to main czy master!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*"         # Wszystkie pliki
          target: "/var/www/cv_kuczynski"
          strip_components: 0 # Nie usuwaj folderów, jeśli masz tam np. /css /js
          rm: true            # CZYŚCI folder przed kopią - to ważne!
